WebApp/Controllers/ShippingController.cs
using Application.Interface;
using AutoMapper;
using Core.Entities;
using Core.Utilities.Results;
using DataAccess.Interfaces;
using Entities.Concrete;
using Entities.Dtos;
using Entities.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
//using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Metadata.Edm;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using X.PagedList;
using static Entities.Enums.Enums;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace WebApp.Controllers
{
    [Authorize(Policy = "AdminMagazaDepo")]
    public class ShippingController : Controller
    {
        private readonly IShippingServices _shippingServices;
        private readonly IShippingDetailsServices _shippingDetailsServices;
        private readonly IColorServices _colorServices;
        private readonly ITempServices _tempServices;
        readonly IProductServices _productServices;
        readonly IStockServices _stockServices;
        readonly IMapper _mapper;
        private IHttpContextAccessor _httpContextAccessor;
        private readonly ITenantServices _tenantServices;
        readonly IAllStockListDal _allStockListDal;


        public ShippingController(IShippingServices shippingServices, IColorServices colorServices, IProductServices productServices, IStockServices stockServices, IShippingDetailsServices shippingDetailsServices, IMapper mapper, IHttpContextAccessor httpContextAccessor, ITenantServices tenantServices, ITempServices tempServices, IAllStockListDal allStockListDal)
        {
            _shippingServices = shippingServices;
            _colorServices = colorServices;
            _productServices = productServices;
            _stockServices = stockServices;
            _shippingDetailsServices = shippingDetailsServices;
            _mapper = mapper;
            _httpContextAccessor = httpContextAccessor;
            _tenantServices = tenantServices;
            _tempServices = tempServices;
            _allStockListDal = allStockListDal;
        }

        //public async Task<IActionResult> ShippingIndex(int page = 1)
        //{///mapping sorunu

        //    var magazaMi = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value;
        //    //User.Claims.FirstOrDefault(a=>a.)

        //    if (magazaMi.ToLower() == "magaza")
        //    {
        //        var res2 = await _shippingServices.IndexIcınGetirMagaza();
        //        ViewBag.Yetki = true;
        //        return View(res2.ToPagedList(page, 12));
        //    }
        //    else if (magazaMi.ToLower() == "admin")
        //    {
        //        ViewBag.Yetki = true;
        //    }
        //    else
        //    {
        //        ViewBag.Yetki = null;
        //    }
        //    var res = await _shippingServices.IndexIcınGetir();
        //    return View(res.ToPagedList(page, 12));

        //}
        public async Task<IActionResult> ShippingIndex(int page = 1)
        {///mapping sorunu

            var magazaMi = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role).Value;
            //User.Claims.FirstOrDefault(a=>a.)
            //if (magazaMi.ToLower() == "admin")
            //{
            //}
            //else
            //{
            //    ViewBag.Yetki = null;
            //}
            ViewBag.Yetki = true;
            if (magazaMi.ToLower() == "depo")
            {
                ViewBag.depoMu = true;
            }
            else
            {
                ViewBag.depoMu = null;
            }



            return View();

        }
        public async Task<IActionResult> ShippingIndexjson(string date)
        {///mapping sorunu

            var dates = new DateTime(Convert.ToInt32(date), 01, 01);
            var res = await _shippingServices.IndexIcınGetir(dates);
            var qq = JsonConvert.SerializeObject(res);
            return Json(qq);

        }
        public async Task<IActionResult> ChangePriceShipping(long shippingId, string newPrice)
        {///mapping sorunu

            try
            {
                if (String.IsNullOrEmpty(newPrice))
                {
                    return Json("Geçerli bir değer giriniz, Başarısız");
                }
                decimal values = decimal.Parse(newPrice, CultureInfo.CurrentCulture);
                var sp = await _shippingDetailsServices.GetById(shippingId);
                var shipping = await _shippingServices.GetById(sp.Data.ShippinbgId);

                ///sipariş ana fiyat güncellendi
                if (shipping.Data != null)
                {
                    string formattedString = shipping.Data.SiparisTutari;
                    decimal siparisTutari = decimal.Parse(formattedString, CultureInfo.CurrentCulture);
                    //if (siparisTutari > sp.Data.Price)
                    //{ }
                    var yeniSiparisTutari = (sp.Data.ShippingCount.Value * values);

                    siparisTutari = siparisTutari - sp.Data.Price; // eski tutar
                    siparisTutari = siparisTutari + yeniSiparisTutari; // yeni tutar

                    shipping.Data.SiparisTutari = siparisTutari.ToString();
                    await _shippingServices.UpdateAll(shipping.Data);
                }

                //sipariş detay fiyatı güncellenbdi
                sp.Data.UnitePrice = values;

                var res = await _shippingDetailsServices.UpdateAll(sp.Data);
                return Json("İşlem Başarılı");
            }
            catch (Exception)
            {
                return Json("işlem Başarısız");
            }

        }
        public async Task<IActionResult> UpdateFinishShippingListView(long spId)
        {

            if (spId != 0)
            {
                var result = await _tempServices.UpdateFinishShippingListView(spId);
                if (result == null || result.Count == 0)
                {
                    ViewBag.Uyari = true;
                    result = new List<ShippingProduct>()
                    {
                        new ShippingProduct()
                        {
                            ShippingId=0,
                            ShippingDetailsId=0
                        }
                    };
                }
                else
                {
                    ViewBag.Uyari = false;
                }
                return View("UpdateFinishShipping", result);
            }
            return BadRequest();
        }

        public async Task<IActionResult> ShippingDetailsUpdatePrice(long spId)
        {

            if (spId != 0)
            {
                var result = await _shippingDetailsServices.UpdateShippingPrice(spId);
                if (result == null || result.Count == 0)
                {
                    ViewBag.Uyari = true;
                    result = new List<ShippingDetails>()
                    {
                        new ShippingDetails()
                        {
                            ShippinbgId=0,
                        }
                    };
                }
                else
                {
                    ViewBag.Uyari = false;
                }
                return View("ShippingDetailsUpdatePrice", result);
            }
            return BadRequest();
        }

        public async Task<IActionResult> ShippingDetailsAddNewProduct(long spId)
        {

            if (spId != 0)
            {
                var result = await _shippingDetailsServices.GetShippingConfirmList(spId);

                ViewBag.Ids = spId;

                var urunler = await ProductUpdateForShipping(spId);
           
                //var xdd= urunler.GroupBy(a => a.ProductId).Distinct().ToList();
                ViewBag.Urun = urunler
                .GroupBy(u => u.ProductId)
                .Select(g => g.First())
                .ToList();
           var shipping = await _tempServices.GetParticalShipping(spId);
                if (shipping == null || shipping.Count==0)
                {

                    var liste = new List<ShippingProduct>();
                    liste.Add(new ShippingProduct());
                    ViewBag.Renkli = liste;
                }
                else
                {
                    ViewBag.Renkli = shipping;
                }



                return View("ShippingDetailsAddNewProduct", result);
            }
            return BadRequest();
        }
        public async Task<IActionResult> UruneEkle(long spId, long productId, long adet)
        {
            if (adet != 0)
            {
                var model = await _shippingDetailsServices.GetShippingDetailsForShippingId(spId, productId);

                var result = await _shippingDetailsServices.GetById(model.Id);

                result.Data.Amount = result.Data.Amount + adet;
                result.Data.ShippingCount += adet;
                await _shippingDetailsServices.UpdateAll(result.Data);


                var shipping = await _shippingServices.GetById(spId);

                shipping.Data.ShippingCount = (Convert.ToInt64(shipping.Data.ShippingCount) + adet).ToString();
                shipping.Data.IsComplated = false;

                await _shippingServices.UpdateAll(shipping.Data);

                return Json("ok");
            }

            return Json("-1");
        }

        public async Task<IActionResult> UrundenCikart(long spId, long productId, long adet, bool sil)
        {
            try
            {

                if (sil)
                {
                    //sipariş detayı silindi
                    var urun = await _shippingDetailsServices.GetShippingDetailsForShippingId(spId, productId);

WebApp/Views/Shipping/AddShippingDetailsColorPartical.cshtml
@*@using PagedList;
@using PagedList.Core.Mvc;*@
@*@using PagedList.Mvc;*@
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@model IPagedList<Entities.Concrete.Color>

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Renk Ekle</h4>
            @*<p class="card-description">

            </p>*@
            @*     <form id="ProductForm" >*@
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Renk</th>
                            <th>Miktar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                        }
                        @foreach (var item in Model)
                        {
                            <tr>
                                @* <td hidden><input class="form-group" type="text" id="color_@i" name="@item.ColorName"></td>*@
                                @*   <td>@item.ColorName </td>
                            <td><input class="typeahead tt-input" type="text" id="colorName_@i" name="@item.ColorName" value="@item.ColorName"></td>*@
                                <td>@item.ColorName <input class="typeahead tt-input" type="text" id="color_@i" name="@item.ColorName" value="@item.Id" hidden></td>
                                <td><input class="typeahead tt-input" type="text" id="colorCount_@i" name="@item.ColorName"></td>
                                @*<td><label class="badge badge-danger">Pending</label></td>*@
                            </tr>
                            i++;
                        }
                        <tr>
                        <td> <button class="btn btn-primary" onclick="Calistir()"> Gönder</button></td>
                        </tr>
                        <tr>
                            <td></td>

                            <td>
                            @{
                                var productCounts2 = ViewBag.ColorCount;
                                if (productCounts2 >= 25 &&36 <= productCounts2)
                                {
                                    productCounts2 = 3;
                                }
                                else if (productCounts2 > 36 )
                                {
                                    productCounts2 = productCounts2 / 12;

                                    }
                                    else if (productCounts2 <= 12)
                                    {
                                        productCounts2 = 1;
                                    }
                                    else if (productCounts2 > 12 && productCounts2 <= 24)
                                    {
                                        productCounts2 = 2;
                                    }
                                }
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    @for (int b = 0; b < productCounts2; b++)
                                    {
                                        <a class="btn btn-outline-secondary" onclick="ShippingColorPartical(@(b+1))" @*href="@Url.Action("AddShippingDetailsColorPartical","Shipping",new{color=b+1})"*@>@(b + 1)</a>
                                    }

                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            @*        </form>*@

        </div>
    </div>

<script>
    function ShippingColorPartical(page){

        $.ajax({
            url: '@Url.Action("AddShippingDetailsColorPartical","Shipping")?color='+page ,
            success: function (data) {
                $('#colorParticalAdd').html(data);
            }
        });


    }

    function Calistir(e) {

         var shippingId = $('#shipping').val();
         console.log(shippingId);
         var productId = RadioChange();
         //console.log($('#productId').val());
         var ColorDto = [];
         var colors = "";
         var count = "";
         for (var b = 1; b <= '@ViewBag.ColorCount'; b++) {
             var gelenCount = $('#color_' + b).val();
             var gelenRenk = $('#colorCount_' + b).val();
             if (gelenCount != "" && gelenCount != 0 && gelenCount != null) {
                 colors += $('#color_' + b).val() + ",";
                 count += $('#colorCount_' + b).val() + ",";
                 var g1 = $('#color_' + b).val() + ",";
                 var g2 = $('#colorCount_' + b).val() + ",";

                 var d = {
                     Count: g2,
                     ColorName: g1,
                 }
                 //var xx=[{
                 //      "Count" :g1,
                 //      "ColorName": g2
                 //  }
                 //]
                 ColorDto.push(d);
             }

         }

         var jsonConvert = JSON.stringify(ColorDto);
        // console.log(jsonConvert);

         var url = '@Url.Action("AddShippingDetails","Shipping")?ShippingId=' + shippingId + '&productId=' + productId;
         $.ajax({
             url:url,
             traditional: true,
             datatype: "JSON",
             async:true,
             method: 'POST',
             data: { "body": jsonConvert },
             success: function () {
                 //alert("tqama");
               //  console.log(shippingId);
                 window.location.reload();
            }
         });


     }
</script>

WebApp/Views/Shipping/Create.cshtml
@using static Entities.Enums.Enums
@model Entities.Concrete.Shippings

<div id="test">
</div>
<form class="form-sample" asp-action="Create" asp-controller="Shipping">
     <div class="row">


    <div class="col-md-2 grid-margin stretch-card">
    </div>

    <div class="col-md-8 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Sipariş Oluştur</h4>
                @* <p class="card-description">
                </p>*@
                <form class="forms-sample" asp-action="Create" asp-controller="Shipping" asp-area="Shipping">
                        <div class="form-group  col-12">
                        <label for="exampleInputUsername1">Firma</label>
                        @Html.DropDownList("TenantId", new SelectList(ViewBag.Tenants, "Id", "TenantName"), new { @class = "form-control",@required="required"  })
                       @* @Html.DropDownListFor(ViewBag.Tenants,(List<SelectList>)ViewBag.Tenants,"Firma Seçin",new{@class="form-control"})*@

                            <div class="form-group">
                                <label for="exampleInputEmail1">Sipariş Adı</label><br />
                            <input type="text" class="form-control" id="SiparisAdi" name="SiparisAdi" placeholder="şipariş Adı" required>
                        </div>
                    </div>
                        <div class="form-group  col-12 ">
                            <label for="exampleInputEmail1">Sipariş Tarihi</label><br />
                        <input type="date" class="form-control" id="RegisterDate" name="RegisterDate" placeholder="Sipariş Tarihi" required>
                    </div>
                        <div class="form-group  col-12 " >
                        <label for="exampleInputEmail1">Sipariş Adresi</label><br />
                        <input type="text" class="form-control" id="Adres" name="Adres" placeholder="Adres"required>
                    </div>
                     
           @*        <div class="row col-12">
                         <div class="form-group col-6">
                            <label for="exampleInputEmail1">Miktar</label>
                            <input type="text" class="form-control" id="ShippingCount" name="ShippingCount" placeholder="Sipariş Miktarı" required>
                     </div>
                        <div class="form-group col-6">
                            <label for="exampleInputEmail1">Tutar</label>
                            <input type="text" class="form-control" id="SiparisTutari" name="SiparisTutari" placeholder="Sipariş Tutarı" required>
                        </div>
                   </div>*@
                  
            @*        <div class="form-check form-check-flat form-check-primary col-12">
                        <label class="form-check-label">
                            <div class="form-group">
                                <input  onchange="KontrolEt()" type="checkbox" class="custom-control-input" data-val="true" id="MagazaMi" name="MagazaMi" value="true">
                                <label class="custom-control-label" for="MagazaMi">Magaza Siparişi Mi ?</label>
                                <input   name="MagazaMi" type="hidden" value="false">
                            </div>
                        </label>
                    </div>*@
                    <center>
                            <button type="submit" class="btn btn-primary col-5">KAYDET</button>
                    </center>
              
                </form>
            </div>
        </div>
    </div>
    </div>
</form>

@section Script{
   <script>
        //new Grid({
        //    columns: ['Name', 'Email'],
        //    data: [
        //        ['John', 'john@example.com'],
        //        ['Mike', 'mike@gmail.com']
        //    ]
        //}).render(document.getElementById('test'));
    
        function KontrolEt(){
            //var magazaMi = false;
            //if ($('#MagazaMi').is(":checked")) {
            //    magazaMi = true;
            //}
            //if (magazaMi) {
            //    swal({
            //        title: "Magaza Siparişi Oluşturuyorsunuz!",
            //        text: "Emin Misiniz?",
            //        icon: "warning",
            //    });
            //} else {
            //}
                swal({
                    title: "Siparişi Oluşturuyorsunuz!",
                    text: "Emin Misiniz?",
                    icon: "warning",
                });


        }
 

    </script>

}

WebApp/Views/Shipping/NewShippingView.cshtml
@{
    long shippingId = ViewBag.Ids;

}
@Html.Hidden("shippingId", shippingId)

<div class="col-md-3 grid-margin stretch-card" style="height:25%;margin:auto">
    <div class="card">
        <div class="card-body">

            <div>
                <span style="font-weight:bold">Arama yap</span> <br />    <br />
                <input class="form-control" type="text" id="search" placeholder="Search.." name="SearchText">
            </div>
            @*<div class="form-group">
                    <label for="exampleInputUsername1">Arama Yap</label>
                    <input type="text" class="form-control" id="searchbar" placeholder="Arama Yap">
                </div>*@<br />
            <button id="gonder" class="btn btn-primary col-12" type="submit">Ara</button>
        </div>
    </div>
</div>
<div class="col-lg-12 grid-margin stretch-card" style="margin-top:25px">
    <div class="card" id="shippingProductNew">

    </div>
</div>

<div>
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card" id="Siparisler">

        </div>
    </div>
</div>

<script>
    

    $(document).ready(function(){

        $.ajax({
            url: '@Url.Action("CheckShippingCofirmListReturn", "Shipping")?spId=' + '@ViewBag.Ids',
            success:function(returnHtml){
                $('#Siparisler').html("");
                $('#Siparisler').html(returnHtml);
            }
        })


    })

    var ShippinbgId = $('#shippingId').val();
    $('#gonder').click(function (e) {
        var ay1;
        var gender1;
        var search;

        const text = $('#search').val();
        if (text.length > 0)
            search = $('#search').val();
        var p = {
            ay1: Number(ay1),
            gender1: Number(gender1),
            SearchText: search,
            Search: true,
        }

        console.log(p);
        $.ajax({
            url: '@Url.Action("NewShippingViewPartical","Shipping")',
            traditional: true,
            data: p,
            success: function (htmls) {
                $('#shippingProductNew').html(htmls);
            }
        })
    });

</script>

WebApp/Views/Shipping/NewShippingViewPartical.cshtml
@model List<Entities.Concrete.Product>

<div class="card-body">
    <h4 class="card-title">Ürün Listesi</h4>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>ÜRÜN</th>
                </tr>

            </thead>
            @* hidden shipping ıd gelecek!!!!!!!!!!*@
            <tbody>
                @{
                    int i = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td><img src="@item.ModelImageUrl" width="25%" /></td>
                        @*  <td hidden><input id="productId" value="@item.Id"  /></td>*@
                        <td>@item.Barcode</td>
                        <td hidden><input type="number" class="form-control" id="ProductId_@i" name="ProductId" placeholder="ıd" value="@item.Id" /></td>
                        <td>@item.ModelCode</td>
                        <td>@item.Gender</td>
                        <td>@item.ModelName</td>
                        @if (item.ProductAges != null)
                        {
                            <td>@item.ProductAges.Name</td>
                        }
                        else
                        {
                            <td></td>
                        }
                        <td>Adet: <input type="number" class="form-control" id="Amounts_@i" name="Amount" placeholder="ADET" /></td>
                        <td>Tutar: <input type="number" class="form-control" id="Prices_@i" name="Price" placeholder="TUTAR" /></td>
                        <td><button class="btn btn-primary" onclick="AddShipping('@item.Id')">Ekle</button></td>
                    </tr>
                    i++;
                }

            </tbody>


        </table>
        <ul class="pagination justify-content-center">
            @{
                int currentPage = ViewBag.CurrentPage;
                int pageSize = ViewBag.PageSize;
                int totalItems = ViewBag.TotalItems;
                int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

                // Previous Button
                if (currentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)" onclick="loadPage(@(currentPage - 1))" aria-label="Previous">
                            <span aria-hidden="true">«</span>
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <span class="page-link">«</span>
                    </li>
                }

                // Page Numbers
                for (int p = 1; p <= totalPages; p++)
                {
                    if (p == currentPage)
                    {
                        <li class="page-item active"><span class="page-link">@p</span></li>
                    }
                    else
                    {
                        <li class="page-item"><a class="page-link" href="javascript:void(0)" onclick="loadPage(@p)">@p</a></li>
                    }
                }

                // Next Button
                if (currentPage < totalPages)
                {
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)" onclick="loadPage(@(currentPage + 1))" aria-label="Next">
                            <span aria-hidden="true">»</span>
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item disabled">
                        <span class="page-link">»</span>
                    </li>
                }
            }
        </ul>
        <script>
            function loadPage(page) {
                var ay1;
                var gender1;
                var search;

                const text = $('#search').val();
                if (text.length > 0)
                    search = $('#search').val();
                var c = {
                    ay1: Number(ay1),
                    gender1: Number(gender1),
                    SearchText: search,
                    Search: true,
                    page: page,
                    pageSize: Number('@ViewBag.PageSize')
                }

                $.ajax({
                url: '@Url.Action("NewShippingViewPartical","Shipping")',
                traditional: true,
                    data: c,
                success: function (htmls) {
                    $('#shippingProductNew').html(htmls);
                }
                 })
            }



        </script>
    </div>
</div>
@section Script{
    }
<script>
    function ClearHtml() {
        console.log(sayacım +"sayaç");
        for (var b = 0; b < sayacım; b++) {
            //console.log((b + 1));
            //console.log($('#Amount_' + (b + 1)).val().toString());
            //$('#Amount_' + (b + 1)).html() ;
            //$('#Price_' + (b + 1)).html();
            document.getElementById('Amounts_' + (b + 1)).value = "";
            document.getElementById('Prices_' + (b + 1)).value = "";
        }
    }
    var sayacım = 0;
    function AddShipping(productId) {

        try {
             const format = (num, decimals) => num.toLocaleString('en-US', {
               minimumFractionDigits: 2,
               maximumFractionDigits: 2,
           });


   sayacım = @Model.Count;
   var stringArray = new Array();
   //stringArray[0] = "item1";
   //stringArray[1] = "item2";
   //stringArray[2] = "item3";

   var convertShippngDto = [];
   var data = new Array();
   var things = {};
   var amount; /*= $('#Amount').val();*/
   var price; /*= $('#Price').val();*/
   var productIds = productId;
   var shippinghId = ShippinbgId;
   var modelCounter = Number(@Model.Count);
   var forSayac= modelCounter;
            console.log(forSayac);


            var totalAdded = 0;



   for (var i = 0; i < forSayac; i++) {

       console.log(i.toString(), $('#Amounts_' + (i + 1)).val() == "");
       console.log(i.toString(), $('#Prices_' + (i + 1)).val()=="");


       if ($('#Amounts_' + (i + 1)).val() == "" || $('#Prices_' + (i + 1)).val() == "") {

           continue;
       }



       if ($('#Amounts_' + (i + 1)).val() != null && $('#Amounts_' + (i + 1)).val()!="") {
           amount = $('#Amounts_' + (i + 1)).val().toString();
       }

       if ($('#Prices_' + (i + 1)).val() != null && $('#Prices_' + (i + 1)).val() != "") {
           price = $('#Prices_' + (i + 1)).val().toString();
       }

       productId = $('#ProductId_' + (i + 1)).val().toString();

       if (price != null && price != undefined && price != "" && amount != null && amount != undefined && amount != "") {
           totalAdded++;
           var sonuc = parseFloat(price) * Number(amount);
           var formatNumber = format(sonuc);
           var format2 = format(parseFloat(price));
           console.log(formatNumber);
           stringArray[i] = { "amount": amount.toString(), "shippinbgId": shippinghId.toString(), "productId": productId.toString(), "price": formatNumber.toString(), "uniteprice": format2.toString() };
       }

     }
 //  console.log(stringArray);
   ClearHtml();
   //var postData = { convertShippngDto: stringArray };
   //console.log(stringArray);

            if (totalAdded > 0) {
                   $.ajax({
                   url: '@Url.Action("ShippingCofirmList2","Shipping")',
                   type: "POST",
                   data: JSON.stringify(stringArray),
                   contentType: 'application/json; charset=utf-8',
                   dataType: 'json',
                   success: function (data) {
                       $('#Siparisler').html("");
                       $('#Siparisler').html(data);
                       for (var i = 1; i < @Model.Count; i++) {
                           $('#Amounts_' + i).html("");
                           $('#Prices_' + i).html("");
                       }
                   },
                   error: function (data) {
                      // console.log(data.responseText);
                       $('#Siparisler').html("");
                       $('#Siparisler').html(data.responseText);

                   }

               })
            }


        } catch (e) {
            console.log(e);
        }
    }




                            //var url = '@Url.Action("AddShippingDetails","Shipping")?ShippingId=' + shippingId + '&productId=' + productId;
                            //$.ajax({
                            //    url: url,
                            //    traditional: true,
                            //    datatype: "JSON",
                            //    async: true,
                            //    method: 'POST',
                            //    data: { "body": jsonConvert },
                            //    success: function () {
                            //        alert("tqama");
                            //        //  console.log(shippingId);
                            //        window.location.reload();
                            //    }
                            //});
</script>