WebApp/Controllers/ColorsController.cs
using Application.Interface;
using AutoMapper;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace WebApp.Controllers
{
    //[Area("Colors")]
    [Authorize(Policy = "AdminMagazaDepo")]
    public class ColorsController : Controller
    {
        readonly IProductServices _productServices;
        readonly IStockServices _stockServices;
        readonly IColorServices _colorServices;
        readonly IMapper _mapper;

        public ColorsController(IProductServices productServices, IStockServices stockServices, IMapper mapper, IColorServices colorServices)
        {
            _mapper = mapper;
            _productServices = productServices;
            _stockServices = stockServices;
            _colorServices = colorServices;
        }
        public async Task<IActionResult> ColorIndex()
        {
            var result = await _colorServices.GetAll();
            return View(result.Data);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Color color)
        {
            var colors = await _colorServices.Add(color);
            return RedirectToAction("ColorIndex");
        }
        public async Task<IActionResult> Update(long id)
        {
            var colors = await _colorServices.GetById(id);
            return View(colors.Data);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Color color)
        {
            var update = _colorServices.UpdateAll(color);
            return RedirectToAction("ColorIndex");
        }

        public async Task<IActionResult> Delete(long id)
        {
            var colors = await _colorServices.GetById(id);
            var delete = await _colorServices.Delete(colors.Data);
            return RedirectToAction("ColorIndex");
        }
    }
}

WebApp/Views/Colors/ColorIndex.cshtml
@model List<Entities.Concrete.Color>
@{
    ViewData["Title"] = "ColorIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-lg-2 grid-margin stretch-card"></div>
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Renkler</h4>
            <span><a class="btn btn-primary" href="@Url.Action("Create","Colors")">Renk Ekle</a></span>
            <div class="table-responsive"   style=" overflow-y: auto; max-height: 600px">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Renk</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@item.ColorName</td>
                            <td></td>
                                <td><a class="btn btn-dark" href="@Url.Action("Update","Colors",new{id=item.Id})">Güncelle</a><a class="btn btn-danger" href="@Url.Action("Delete","Colors",new{id=item.Id})">Sil</a></td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Colors/Create.cshtml
@model Entities.Concrete.Color

@{
    Layout = Layout;
}
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Renk Ekle</h4>
            <p class="card-description">
            </p>
            <form class="forms-sample" asp-action="Create" asp-controller="Colors">
                <div class="form-group">
                    <label for="exampleInputUsername1">Renk Adı</label>
                    <input type="text" class="form-control" id="ColorName" name="ColorName" placeholder="Renk Adı">
                </div>
                <button type="submit" class="btn btn-primary me-2">Ekle</button>
            </form>
        </div>
    </div>
</div>

WebApp/Views/Colors/Update.cshtml
@model Entities.Concrete.Color
@{
    Layout = Layout;
}
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Renk Güncelle</h4>
            <p class="card-description">
            </p>
            <form class="forms-sample" asp-action="Update" asp-controller="Colors">
                @Html.Hidden("Id",Model.Id)
                <div class="form-group">
                    <label for="exampleInputUsername1">Renk Adı</label>
                    <input type="text" class="form-control" id="ColorName" name="ColorName" value="@Model.ColorName" placeholder="Renk Adı">
                </div>
                <button type="submit" class="btn btn-primary me-2">Güncelle</button>
            </form>
        </div>
    </div>
</div>