WebApp/Controllers/TempController.cs
using Application.Interface;
using AutoMapper;
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using X.PagedList;
using System.Collections.Generic;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using DataAccess.Interfaces;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml;
using Core.Utilities.Results;
using DocumentFormat.OpenXml.Packaging;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using static Entities.Enums.Enums;
using System.Globalization;
using System.Web.Providers.Entities;

namespace WebApp.Controllers
{

    [Authorize(Policy = "AdminMagazaDepo")]
    public class TempController : Controller
    {
        readonly IProductServices _productServices;
        readonly IStockServices _stockServices;
        readonly IMagazaStock _magazaRepository;
        readonly IColorServices _colorServices;
        readonly ITempServices _tempServices;
        readonly IShippingDetailsServices _shippingDetailsServices;
        readonly IShippingServices _shippingServices;
        readonly IOrderDateServices _orderDateServices;
        readonly IOrderServices _orderServices;
        readonly IMapper _mapper;
        private readonly IWebHostEnvironment _evn;
        private readonly ITenantServices _tenantServices;

        public TempController(IProductServices productServices, IStockServices stockServices, IMapper mapper, IColorServices colorServices, ITempServices tempServices, IShippingDetailsServices shippingDetailsServices, IOrderDateServices orderDateServices, IOrderServices orderServices, IShippingServices shippingServices, IMagazaStock magazaRepository, IWebHostEnvironment evn, ITenantServices tenantServices)
        {
            _mapper = mapper;
            _productServices = productServices;
            _stockServices = stockServices;
            _colorServices = colorServices;
            _tempServices = tempServices;
            _shippingDetailsServices = shippingDetailsServices;
            _orderDateServices = orderDateServices;
            _orderServices = orderServices;
            _shippingServices = shippingServices;
            _magazaRepository = magazaRepository;
            _evn = evn;
            _tenantServices = tenantServices;
        }
        [Authorize(Policy = "AdminMagazaDepo")]
        public async Task<IActionResult> TempsIndex(int page=1)
        {
            return View();
        }
        [Authorize(Policy = "AdminMagazaDepo")]
        public async Task<IActionResult> TempsIndexReturnJson(string date)
        {
            var datetime = new DateTime(Convert.ToInt32(date), 01, 01);
            var result = await _tempServices.TempIndex(datetime);
            var models = JsonConvert.SerializeObject(result);
            return Json(models);
        }
        /* Depocu aydınlara tıkladı onun siparişlerini görüyor. */
        [Authorize(Policy = "AdminMagazaDepo")]
        public async Task<IActionResult> TenantShipping(long tenantId,string date)
        {
            var magaza = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.Role).Value;
            //if (magaza.ToLower() == "magaza")
            //{
            //    var result2 = await _tempServices.TempMagazaIndex();
            //    return View(result2.FirstOrDefault(a => a.Id == tenantId));
            //}
            //var result = await _tempServices.TenantShippingList(tenantId);
            ViewBag.TenantId = tenantId;
            ViewBag.Date = new DateTime(Convert.ToInt32(date),01,01);
            return View();
        }

        public async Task<IActionResult> TenantShippingJson(long tenantId,DateTime date)
        {
            var magaza = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.Role).Value;
            var result = await _tempServices.TenantShippingList(tenantId,date.Date);
            var qq = JsonConvert.SerializeObject(result);
            return Json(qq);
        }

        //**********////////

        /* Buradi sp porsedur değiştirilecek. Magaza Seesionı doluysa gidip magazanın siparişlerini getirmesi gerekiyor,
          Şu an bütün siparişleri aynı anda getiriyor hatalıııııı!!!!!!!!!

        ve onun üstünde altında 2 tane daha yazmıştım onalra da bak :)
      
        //*************////////
        [Authorize(Policy = "AdminMagazaDepo")]
        public async Task<IActionResult> PrepareOrders(long shippingId, int? page = 1)
        {

           var magazaRol= User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.Role).Value.ToString();
            List<OrderShippingDetailsDto> result = new List<OrderShippingDetailsDto>();
            List<Product> models = new List<Product>();
            if (magazaRol.ToLower()=="magaza")
            {
                result = await _tempServices.OrderShippingProductsMagaza(shippingId);
            }
            else
            {
                //result = await _tempServices.OrderShippingProducts(shippingId);
              
                models = await _tempServices.GetPrepareShipping(shippingId);

            }

            //long count = result.Count();

       
            ViewBag.PageCount = models.Count;
            ViewBag.ShippingId = shippingId;
            //return View(result.ToPagedList(page != null ? (page == 1 ? 1 : page.Value) : 1, 6));            
            return View(models.ToPagedList(page != null ? (page == 1 ? 1 : page.Value) : 1, 6));
        }

        public async Task<IActionResult> ColorPartical(long shippingId, long productId, int? page = 1)
        {

            var magazaRol = User.Claims.FirstOrDefault(a => a.Type == ClaimTypes.Role).Value.ToString();
            List<OrderShippingDetailsDto> result = new List<OrderShippingDetailsDto>();
            List<ColorDtoForShipping> list = new List<ColorDtoForShipping>();

            if (magazaRol.ToLower() == "magaza")
            {
                result = await _tempServices.OrderShippingProductsMagaza(shippingId);
            }
            else
            {
                //result = await _tempServices.OrderShippingProducts(shippingId);
                list = await _tempServices.GetPrepareColorList(shippingId,productId);
            }
       

            // var result2 = result.FirstOrDefault(a => a.ProductId == productId);
            //if (result2!=null)
            //{
            //    ViewBag.PageCount = result2.Color.Count;
            //    ViewBag.ColorShippingCount = result2.Color.Count;
            //}
            //else
            //{
            //    ViewBag.PageCount = 1;
            //    ViewBag.ColorShippingCount = 1;
            //}
            ViewBag.ShippingId = shippingId;
            ViewBag.ProductId = productId;

            
                return PartialView(list.ToPagedList(page.Value, 12));
            //if (result2!=null)
            //{
            //    var  mainResult= result2.Color.ToPagedList(page.Value,12 );
            //    return PartialView(mainResult);
            //}
            //else
            //{
            ////result2.Color.ToPagedList(page != null ? (page == 1 ? 1 : page.Value) : 0, 5);
            //return PartialView(result2);

            //}
        }
        [Authorize(Policy = "AdminMagazaDepo" )]
        public async Task<IActionResult> Update(long id)
        {
            var result = await _tempServices.GetById(id);
            return View(result.Data);
        }
        [HttpPost]
        public IActionResult Update(Temp temp)
        {
            return View();
        }

        [HttpPost]
        public async Task<bool> AddShippingDetails(long ShippingId, long productId, String bodyy, bool refresh)
        {
            var model = JsonConvert.DeserializeObject<List<ColorDto>>(bodyy);
           
            foreach (var item in model)
            {

                Temp tmp = new Temp
                {
                    ShippigId = ShippingId,
                    ProductId = productId,
                    IsComplated = true,
                    IsFinished = false,
                    RegisterDate = DateTime.Now,
          
                };
                item.ColorName = item.ColorName.Replace(",", "");
                item.Count = item.Count.Replace(",", "");
                if (item.ColorName != "" && item.Count != "" && item.ColorName != "," && item.Count != "," && item.Count != "on" && item.ColorName != "on")
                {

                    tmp.ColorId = Convert.ToInt64(item.ColorName);
                    tmp.Count = Convert.ToInt64(item.Count);

                    var check = await _tempServices.GetAll(a => a.ProductId == productId && a.ColorId == Convert.ToInt64(item.ColorName) && a.ShippigId == ShippingId&&!a.IsFinished);
                    if (check.Data.Count > 0)
                    {
                      /*Temp'de eşit olan sp,p,color'a ekleme yapıldı   */
                        var query = check.Data.FirstOrDefault();
                        query.Count = query.Count + Convert.ToInt64(item.Count);
                        query.IsComplated = true;
                        await _tempServices.UpdateAll(query);
                       /*               ************               */

                        var shipping = await _shippingDetailsServices.GetAll(a => a.ShippinbgId == ShippingId && a.ProductId == productId && a.ColorId == Convert.ToInt32(item.ColorName));
                       /* Sipariş detayı bulundu*/

                        if (shipping.Data.Count > 0)
                        {
                            /* sipariş detayından gelen miktar düşüldü */
                            var querys = shipping.Data.FirstOrDefault();
                            if (querys != null)
                            {
                                if (querys.ShippingCount >0)

WebApp/Views/Temp/ColorPartical.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;

@model IPagedList< Entities.Dtos.ColorDtoForShipping>

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Renk/Sipariş Miktarı</h4>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Barcode</th>
                            <th>Renk</th>
                            <th>Stock Miktarı</th>
@*                            <th>Sipariş Miktarı</th>
*@              
                        @*    <th>Sale</th>
                            <th>Status</th>*@
                        </tr>
                    </thead>
                    <tbody>


                         @{
                            int i = 1;
                        }
                  @if (Model!=null)
                    {
                       if (Model.Count>0)
                        {
                            @Html.Hidden("colorCountScript",Model.Count)
                            @foreach (var item in Model)
                            {
                                if (Convert.ToInt64(item.StockCount) > 0)
                                {
                                    <tr>
                                        <td>@item.RenkBarcode</td>
                                        <td hidden> <input class="typeahead tt-input" type="text" id="RenkBarcode_@i" name="@item.RenkBarcode" value="@item.RenkBarcode" hidden></td>
                                        <td>@item.ColorName</td>
                                        <td hidden> <input class="typeahead tt-input" type="text" id="color_@i" name="@item.ColorName" value="@item.ColorId" hidden></td>
                                        <td>@item.StockCount <input id="StockCount_@i" value="@item.StockCount" hidden></td>
                                        <td>@item.shippingColorCount <input id="colorCountForScript_@i" value="@item.shippingColorCount" hidden></td>
                                        <td><input class="form-control" min="0" max="@item.shippingColorCount" type="number" id="colorCount_@i" name="@item.ColorName"></td>
                                        @*       <td><input  class="form-control" type="number" id="shippingColorCount" name="shippingColorCount" /></td>*@
                                    </tr>
                                    i++;
                                }
                            }
                        }
                        
                    }
                 
                            <tr>
                                <td>
                                     @if (Model!=null)
                    {
                       if (Model.Count>0)
                        {
                                    <button onclick="Calistir()" type="button" class="btn btn-info">Kaydet</button>
                        }}
                            </tr>
             
                    </tbody>
                    <tr>

                        <td>
                        @*    @{
                                var productCounts = ViewBag.PageCount;
                                if (productCounts >= 10)
                                {
                                    productCounts = productCounts / 5;
                                }
                                else if (productCounts <= 5)
                                {
                                    productCounts = 1;
                                }
                                else if (productCounts > 5 && productCounts <= 9)
                                {
                                    productCounts = 2;
                                }
                            }
                            <div class="btn-group" role="group" aria-label="Basic example">
                                @for (int b = 0; b < productCounts; b++)
                                {
                                    <a class="btn btn-outline-secondary" onclick="pageColor(@(b+1))">@(b + 1)</a>
                                }

                            </div>*@

                        @{
                            var productCounts2 = ViewBag.PageCount;
                            if (productCounts2 >= 25 && 36 <= productCounts2)
                            {
                                productCounts2 = 3;
                            }
                            else if (productCounts2 > 36)
                            {
                                productCounts2 = productCounts2 / 12;

                            }
                            else if (productCounts2 <= 12)
                            {
                                productCounts2 = 1;
                            }
                            else if (productCounts2 > 12 && productCounts2 <= 24)
                            {
                                productCounts2 = 2;
                            }
                        }
                        <div class="btn-group" role="group" aria-label="Basic example">
                            @for (int b = 0; b < productCounts2; b++)
                            {
                                <a class="btn btn-outline-secondary" onclick="pageColor(@(b+1))" @*href="@Url.Action("AddShippingDetailsColorPartical","Shipping",new{color=b+1})"*@>@(b + 1)</a>
                            }

                        </div>

                        </td>
                    </tr>
                </table>
            </div>
                   
        </div>
    </div>
 
 @*<script>

     function pageColor(page){
         var shippingId= $('#shippingId').val();
         var productId=$('productId').val();
        var url = '@Url.Action("ColorPartical","Temp")?shippingId='+shippingId+'&productId='+productId+"&page="+page 

     }
 </script>*@

WebApp/Views/Temp/IsComplatedShipping.cshtml
@model List<Entities.Dtos.ShippingProduct>


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Eklenen Ürünler</h4>
            <div class="col-12 row">

                <div class="col-10" style="width:80%">
                </div>
                <div class="col-2" style="width:20%">
                    <button onclick="SiparisOnayi2()" type="button" class="btn btn-secondary btn-rounded btn-fw">Siparişi Kaydet</button>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Model Kodu
                            </th>
                            <th>
                                Model Adı
                            </th>
                            <th>
                                Renk
                            </th>
                            <th>
                                Adet
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                        }
                        @Html.Hidden("ShippingCountScript",Model.Count)
                        @foreach (var item in Model)
                        {


                        //***////////////////////


                            @*   siparişlerimde hala görünüyor. engellemek için siparişi tamam la dediğinde toplam idler,shippingıD color ve productları gönderip
                        shipping detail sayfasında Iscompalted ve finis true olmalı*@

                            //***////////////////////
                            //***////////////////////
                            if (item.Count > 0)
                            {
                                @Html.Hidden("shippingId",item.ShippingId)
                        <tr>
                            @*  <td class="py-1">
        <img src="../../images/faces/face1.jpg" alt="image">
        </td>*@
                            <td>
                                @*          @Html.Hidden("productIdComplated_"+i,item.ProductId)*@
                                @item.ModelCode
                            </td>
                            <td>
                                <input type="text" id="productIdComplated_@i" value="@item.ProductId" hidden>
                                @*          @Html.Hidden("productIdComplated_"+i,item.ProductId)*@
                                @item.ProductName
                            </td>
                            @*   <td>
        <div class="progress">
        <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        </td>*@
                            <td>
                                <input type="text" id="colorNameComplated_@i" value="   @item.ColorName" hidden>
                                @*      @Html.Hidden("colorNameComplated_"+i,item.ColorName)*@
                                <input type="text" id="colorIdComplated_@i" value="@item.ColorId" hidden>
                                @*   @Html.Hidden("colorIdComplated_"+i,item.ColorId)*@
                                @item.ColorName
                            </td>
                            <td>
                                <input type="text" id="colorCountComplated_@i" value=" @item.Count" hidden>
                                @*    @Html.Hidden("colorCountComplated_"+i,item.Count)*@
                                @item.Count
                            </td>
                            <td>
                                @*   <button type="button" class="btn btn-warning btn-xs legitRipple pull-right" onclick="Delete('@item.ProductId','@item.ColorId','@item.ShippingId','@item.Count')">
                Sil
            </button>*@
                                <a class="btn btn-warning btn-xs legitRipple pull-right" href="@Url.Action("Delete","Temp",new{tempId=item.TempId,count=item.Count})"> Sil</a>
                            </td>
                        </tr>
                                i++;
                            }
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebApp/Views/Temp/ShippingFinish.cshtml
@model List<Entities.Dtos.ShippingProduct>


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Sipariş Fiyatlandırma</h4>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Model Kodu</th>
                            <th>Model Adı</th>
                            <th>Yaş</th>
                            <th>Cinsiyet</th>
                            <th>Rengi</th>
                            <th>Miktar</th>
                            <th>Birim Fiyatı</th>
                            <th>Tutarı</th>
                          
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 1;
                        }
                        @foreach (var item in Model)
                        {
                            foreach (var item2 in item.ShippingLists)
                            {
                                @Html.Hidden("modelCount",item.ShippingLists.Count)
                                if (item2.Count>0)
                                {
                                    
                                    <tr>
                                        <td hidden><input id="productIdd_@i" value="@item2.ProductId" /></td>
                                        <td hidden><input id="shippingIdd_@i" value="@item.ShippingId" /></td>
                                        <td hidden><input id="colorIdd_@i" value="@item2.ColorId" /></td>
                                         @{Console.WriteLine(item2.ColorId);}
                                        <td>@item2.ModelCode</td>
                                        <td>@item2.ProductName</td>
                                        <td>@item2.Age</td>
                                        <td>@item2.Gender</td>
                                        <td>@item2.ColorName</td>
                                        <td><input id="adet_@i" value="@item2.Count" hidden> @item2.Count</td>
                                        <td> <input type="number" id="birimFiyat_@i" placeholder="Birim Fiyatı"/></td>
                                    <td> <span id="sonuc_@i"></span>₺</td>
                                      @*  <td><label class="badge badge-danger">Pending</label></td>*@
                                    </tr>
                                i++;
                                }
                            }
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                  
                                        <button type="button" id="Hesapla" @*onclick="Hesapla()"*@ class="btn btn-dark btn-rounded btn-icon">
                                            Hesapla
                                        </button>
                                    <button type="button" id="fiyatlandirma" onclick="Faturala()" class="btn btn-primary btn-rounded btn-icon" hidden>
                                            Fiyatlandırmayı Bitir
                                        </button>
                                  
                                </td>
                                <td>
                                  <span id="totalCount"></span>₺
                                </td>
                            </tr>
                        }
                    
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Script{

    <script>
       
        $('#Hesapla').on('click',function(){

              var count= parseInt( $('#modelCount').val());
           var total=0;

           var denee=0;
            for (var i = 1; i <=count;i++){

                var adet = $('#adet_' + i).val();
                console.log(adet+'adet');
                var birim = $('#birimFiyat_' + i).val();
                console.log(birim + 'birim');
                var sonuc = (Number(adet) * Number(birim)/*.toPrecision(3)*/);
                console.log(sonuc+"sonuc");
                $('#sonuc_' + i).html(sonuc.toPrecision(5));
                total+=sonuc;

            }

            $('#totalCount').html(total.toPrecision(5));
          $('#fiyatlandirma').removeAttr('hidden');

        })
        //function Hesapla(){
          
        //}
        function Faturala(){


            swal({
                title: "Fiyatlandırmayı Tamamla",
                text: "Emin Misiniz?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
                buttons: ["Hayır", "Evet"],
            }).then((willDelete) => {
                if (willDelete) {
                    swal("", {
                        icon: "success",
                    });


                    var shippingArray = [];
                    var totalresult2 = $('#totalCount').text();
                    var count = parseInt($('#modelCount').val());
                    var productCountForDetails = "";
                    for (var i = 1; i <= count; i++) {
                        var productId = $('#productIdd_' + i).val();
                        var shippingId = $('#shippingIdd_' + i).val();
                        var colorId = $('#colorIdd_' + i).val();
                        var price = $('#sonuc_' + i).text();
                        var birim = $('#birimFiyat_' + i).val();
                        var adet = $('#adet_' + i).val();
                        var items = {
                            ProductId: productId,
                            ColorId: colorId,
                            ShippingId: shippingId,
                            Price: price,
                            UnitePrice: birim,
                            TotalPrice: totalresult2,
                            ProductCount: adet,
                        }

                        shippingArray.push(items);
                    }

                    var jsonConvert = JSON.stringify(shippingArray);
                    var url = '@Url.Action("CloseOrder","Temp")?tenantId=' + '@ViewBag.TenantId';
                    $.ajax({
                        url: url,
                        traditional: true,
                        datatype: "JSON",
                        async: true,
                        method: 'POST',
                        data: { "body": jsonConvert },
                        success: function () {
                            window.location.href = '@Url.Action("ShippingFinishFirstView","Temp")';
                        }
                    });
                }});



          

        }
    </script>
}

WebApp/Views/Temp/ShippingFinishFirstView.cshtml
@*@using PagedList.Core.Mvc;*@
@using X.PagedList.Mvc.Core;
@using X.PagedList;

@{
    Layout = Layout;
}
@model IPagedList<Entities.Dtos.ShippingProduct>


<div class="col-lg-2 grid-margin stretch-card">
</div>

<div class="col-lg-7 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
           @* <h4 class="card-title">Tamamlanan Siparişler</h4>*@
            <p class="card-description">
                <h4 class="card-title">Tamamlanan Siparişler</h4>
            </p>
            <div class="table-responsive">
                <table class="table ">
                    <thead>
                        <tr>
                            <th>
                                Firma Adı
                            </th>
                            <th>
                             
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model!=null)
                        {
                            if (Model.Count > 0)
                            {
                                foreach (var item in Model)
                                {

                                    <tr>
                                        <td>
                                            @item.TenantName
                                        </td>
                                        <td>
                                            <a class="btn btn-primary" href="@Url.Action("ShippingFinish","Temp",new{tenantId=item.TenantId,shippingId=item.ShippingId})">Fiyatlandır ve Döküm Al</a>
                                        </td>

                                    </tr>
                                }

                            }
                     
                        }
                     @*
                        @{
                            var productCounts = ViewBag.PageCount;
                            if (productCounts >= 10)
                            {
                                productCounts = productCounts / 5;
                            }
                            else if (productCounts <= 5)
                            {
                                productCounts = 1;
                            }
                            else if (productCounts > 5 && productCounts <= 9)
                            {
                                productCounts = 2;
                            }
                        }*@
                        @if (Model.Count > 0)
                        {
                    <tr>
                        <td>
                                @*<div class="btn-group" role="group" aria-label="Basic example">
                                    @for (int b = 0; b < productCounts; b++)
                                    {
                                        <a class="btn btn-outline-secondary" href="@Url.Action("ShippingFinishFirstView","Temp",new{page=b+1})">@(b + 1)</a>
                                    }

                                </div>*@
                                   <div class="btn-group" role="group" aria-label="Basic example">
                                        @Html.PagedListPager((IPagedList)Model,page=>Url.Action("ShippingFinishFirstView",new{page}),
                            new X.PagedList.Web.Common.PagedListRenderOptions {
                            DisplayLinkToIndividualPages = true,
                            DisplayPageCountAndCurrentLocation = false,
                            MaximumPageNumbersToDisplay = 10,
                            LiElementClasses = new string[] { "page-item" },
                            PageClasses = new string[] { "page-link" }})
                            </div>
                        </td>
                    </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>